# -*- coding: utf-8 -*-
"""
    @credit: Aisha Ali-Gombe (aaligombe@towson.edu)
    @contributors: Alexandre Blanchon, Arthur Belleville, Corentin Jeudy

    Brief: artTypes offsets - Android 9 (64 bits)
"""

types = {
	'IndirectReferenceTable': [0x38, {
		'segment_state_': [0],
		'table_mem_map_': [8],
		'table_': [16],
		'kind_': [24],
		'max_entries_': [32],
		'current_num_holes_': [40],
		'last_known_previous_state_': [48],
		'resizable_': [52],
	}],

	'IRTSegmentState': [0x4, {
		'top_index': [0],
	}],

	'IrtEntry': [0x10, {
		'serial_': [0],
		'references_': [4],
	}],

	'GcRoot<art::mirror::Object>': [0x4, {
		'root_': [0],
	}],

	'Thread': [0xa18, {
		'tls32_': [0],
		'tls64_': [72],
		'tlsPtr_': [136],
		'wait_mutex_': [2504],
		'wait_cond_': [2512],
		'wait_monitor_': [2520],
		'debug_disallow_read_barrier_': [2528],
		'poison_object_cookie_': [2536],
		'checkpoint_overflow_': [2544],
		'custom_tls_': [2568],
		'can_call_into_java_': [2576],
	}],

	'ArtMethod': [0x28, {
		'declaring_class_': [0],
		'access_flags_': [4],
		'dex_code_item_offset_': [8],
		'dex_method_index_': [12],
		'method_index_': [16],
		'hotness_count_': [18],
		'ptr_sized_fields_': [24],
	}],

	'Monitor': [0x90, {
		'monitor_lock_': [0],
		'monitor_contenders_': [56],
		'num_waiters_': [80],
		'owner_': [88],
		'lock_count_': [96],
		'obj_': [100],
		'wait_set_': [104],
		'hash_code_': [112],
		'locking_method_': [120],
		'locking_dex_pc_': [128],
		'monitor_id_': [132],
		'next_free_': [136],
	}],

	'ArtField': [0x10, {
		'declaring_class_': [0],
		'access_flags_': [4],
		'field_dex_idx_': [8],
		'offset_': [12],
	}],

	'Runtime': [0x628, {
		'callee_save_methods_': [0],
		'pre_allocated_OutOfMemoryError_': [48],
		'pre_allocated_NoClassDefFoundError_': [52],
		'resolution_method_': [56],
		'imt_conflict_method_': [64],
		'imt_unimplemented_method_': [72],
		'sentinel_': [80],
		'instruction_set_': [84],
		'callee_save_method_frame_infos_': [88],
		'compiler_callbacks_': [160],
		'is_zygote_': [168],
		'must_relocate_': [169],
		'is_concurrent_gc_enabled_': [170],
		'is_explicit_gc_disabled_': [171],
		'dex2oat_enabled_': [172],
		'image_dex2oat_enabled_': [173],
		'compiler_executable_': [176],
		'patchoat_executable_': [200],
		'compiler_options_': [224],
		'image_compiler_options_': [248],
		'image_location_': [272],
		'boot_class_path_string_': [296],
		'class_path_string_': [320],
		'properties_': [344],
		'agent_specs_': [368],
		'agents_': [392],
		'plugins_': [416],
		'default_stack_size_': [440],
		'heap_': [448],
		'jit_arena_pool_': [456],
		'arena_pool_': [464],
		'low_4gb_arena_pool_': [472],
		'linear_alloc_': [480],
		'max_spins_before_thin_lock_inflation_': [488],
		'monitor_list_': [496],
		'monitor_pool_': [504],
		'thread_list_': [512],
		'intern_table_': [520],
		'class_linker_': [528],
		'signal_catcher_': [536],
		'use_tombstoned_traces_': [544],
		'stack_trace_file_': [552],
		'java_vm_': [576],
		'jit_': [584],
		'jit_options_': [592],
		'fault_message_lock_': [600],
		'fault_message_': [656],
		'threads_being_born_': [680],
		'shutdown_cond_': [688],
		'shutting_down_': [696],
		'shutting_down_started_': [697],
		'started_': [698],
		'finished_starting_': [699],
		'vfprintf_': [704],
		'exit_': [712],
		'abort_': [720],
		'stats_enabled_': [728],
		'stats_': [732],
		'is_running_on_memory_tool_': [788],
		'trace_config_': [792],
		'instrumentation_': [800],
		'main_thread_group_': [1216],
		'system_thread_group_': [1224],
		'system_class_loader_': [1232],
		'dump_gc_performance_on_shutdown_': [1240],
		'preinitialization_transactions_': [1248],
		'verify_': [1272],
		'allow_dex_file_fallback_': [1273],
		'cpu_abilist_': [1280],
		'target_sdk_version_': [1304],
		'implicit_null_checks_': [1308],
		'implicit_so_checks_': [1309],
		'implicit_suspend_checks_': [1310],
		'no_sig_chain_': [1311],
		'force_native_bridge_': [1312],
		'is_native_bridge_loaded_': [1313],
		'is_native_debuggable_': [1314],
		'async_exceptions_thrown_': [1315],
		'is_java_debuggable_': [1316],
		'zygote_max_failed_boots_': [1320],
		'experimental_flags_': [1324],
		'fingerprint_': [1328],
		'oat_file_manager_': [1352],
		'is_low_memory_mode_': [1360],
		'madvise_random_access_': [1361],
		'safe_mode_': [1362],
		'hidden_api_policy_': [1364],
		'hidden_api_exemptions_': [1368],
		'pending_hidden_api_warning_': [1392],
		'dedupe_hidden_api_warnings_': [1393],
		'always_set_hidden_api_warning_flag_': [1394],
		'hidden_api_access_event_log_rate_': [1396],
		'process_package_name_': [1400],
		'dump_native_stack_on_sig_quit_': [1424],
		'pruned_dalvik_cache_': [1425],
		'process_state_': [1428],
		'zygote_no_threads_': [1432],
		'jdwp_options_': [1440],
		'jdwp_provider_': [1464],
		'env_snapshot_': [1472],
		'system_weak_holders_': [1504],
		'callbacks_': [1528],
		'deoptimization_counts_': [1536],
		'protected_fault_page_': [1568],
	}],

	'ThreadList': [0x20c8, {
		'allocated_ids_': [0],
		'list_': [8192],
		'suspend_all_count_': [8216],
		'debug_suspend_all_count_': [8220],
		'unregistering_count_': [8224],
		'suspend_all_historam_': [8232],
		'long_suspend_': [8368],
		'shut_down_': [8369],
		'thread_suspend_timeout_ns_': [8376],
		'empty_checkpoint_barrier_': [8384],
	}],

	'JavaVMExt': [0x108, {
		'runtime_': [8],
		'check_jni_abort_hook_': [16],
		'check_jni_abort_hook_data_': [24],
		'check_jni_': [32],
		'force_copy_': [33],
		'tracing_enabled_': [34],
		'trace_': [40],
		'globals_': [64],
		'libraries_': [120],
		'unchecked_functions_': [128],
		'weak_globals_': [136],
		'allow_accessing_weak_globals_': [192],
		'weak_globals_add_condition_': [200],
		'env_hooks_': [224],
		'enable_allocation_tracking_delta_': [248],
		'allocation_tracking_enabled_': [256],
		'old_allocation_tracking_state_': [257],
	}],

	'OatFile': [0x110, {
		'_vptr$OatFile': [0],
		'location_': [8],
		'vdex_': [32],
		'begin_': [40],
		'end_': [48],
		'bss_begin_': [56],
		'bss_end_': [64],
		'bss_methods_': [72],
		'bss_roots_': [80],
		'is_executable_': [88],
		'vdex_begin_': [96],
		'vdex_end_': [104],
		'oat_dex_files_storage_': [112],
		'oat_dex_files_': [136],
		'secondary_lookup_lock_': [160],
		'secondary_oat_dex_files_': [216],
		'string_cache_': [240],
		'uncompressed_dex_files_': [264],
	}],

	'ProtoId': [0xc, {
		'shorty_idx_': [0],
		'return_type_idx_': [4],
		'pad_': [6],
		'parameters_off_': [8],
	}],

	'ClassDef': [0x20, {
		'class_idx_': [0],
		'pad1_': [2],
		'access_flags_': [4],
		'superclass_idx_': [8],
		'pad2_': [10],
		'interfaces_off_': [12],
		'source_file_idx_': [16],
		'annotations_off_': [20],
		'class_data_off_': [24],
		'static_values_off_': [28],
	}],

	'CompressedReference<art::mirror::Object>': [0x4, {
	}],

	'ObjectReference<false, art::mirror::Object>': [0x4, {
		'reference_': [0],
	}],

	'Object': [0x8, {
		'klass_': [0],
		'monitor_': [4],
	}],

	'Class': [0x78, {
		'class_loader_': [8],
		'component_type_': [12],
		'dex_cache_': [16],
		'ext_data_': [20],
		'iftable_': [24],
		'name_': [28],
		'super_class_': [32],
		'vtable_': [36],
		'ifields_': [40],
		'methods_': [48],
		'sfields_': [56],
		'access_flags_': [64],
		'class_flags_': [68],
		'class_size_': [72],
		'clinit_thread_id_': [76],
		'dex_class_def_idx_': [80],
		'dex_type_idx_': [84],
		'num_reference_instance_fields_': [88],
		'num_reference_static_fields_': [92],
		'object_size_': [96],
		'object_size_alloc_fast_path_': [100],
		'primitive_type_': [104],
		'reference_instance_offsets_': [108],
		'status_': [112],
		'copied_methods_offset_': [116],
		'virtual_methods_offset_': [118],
	}],

	'DexCache': [0x5c, {
		'location_': [8],
		'num_resolved_call_sites_': [12],
		'dex_file_': [16],
		'resolved_call_sites_': [24],
		'resolved_fields_': [32],
		'resolved_method_types_': [40],
		'resolved_methods_': [48],
		'resolved_types_': [56],
		'strings_': [64],
		'num_resolved_fields_': [72],
		'num_resolved_method_types_': [76],
		'num_resolved_methods_': [80],
		'num_resolved_types_': [84],
		'num_strings_': [88],
	}],

	'String': [0x10, {
		'count_': [8],
		'hash_code_': [12],
		'': [16],
	}],

	'tls_32bit_sized_values': [0x48, {
		'state_and_flags': [0],
		'suspend_count': [4],
		'debug_suspend_count': [8],
		'thin_lock_thread_id': [12],
		'tid': [16],
		'daemon': [20],
		'throwing_OutOfMemoryError': [24],
		'no_thread_suspension': [28],
		'thread_exit_check_count': [32],
		'handling_signal_': [36],
		'is_transitioning_to_runnable': [40],
		'ready_for_debug_invoke': [44],
		'debug_method_entry_': [48],
		'is_gc_marking': [52],
		'interrupted': [56],
		'weak_ref_access_enabled': [60],
		'disable_thread_flip_count': [64],
		'user_code_suspend_count': [68],
		'as_struct': [0],
		'as_atomic_int': [0],
		'as_int': [0],
	}],

	'tls_64bit_sized_values': [0x40, {
		'trace_clock_base': [0],
		'stats': [8],
	}],

	'tls_ptr_sized_values': [0x940, {
		'card_table': [0],
		'exception': [8],
		'stack_end': [16],
		'managed_stack': [24],
		'suspend_trigger': [48],
		'jni_env': [56],
		'tmp_jni_env': [64],
		'self': [72],
		'opeer': [80],
		'jpeer': [88],
		'stack_begin': [96],
		'stack_size': [104],
		'deps_or_stack_trace_sample': [112],
		'wait_next': [120],
		'monitor_enter_object': [128],
		'top_handle_scope': [136],
		'class_loader_override': [144],
		'long_jump_context': [152],
		'instrumentation_stack': [160],
		'debug_invoke_req': [168],
		'single_step_control': [176],
		'stacked_shadow_frame_record': [184],
		'deoptimization_context_stack': [192],
		'frame_id_to_shadow_frame': [200],
		'name': [208],
		'pthread_self': [216],
		'last_no_thread_suspension_cause': [224],
		'checkpoint_function': [232],
		'active_suspend_barriers': [240],
		'thread_local_start': [264],
		'thread_local_pos': [272],
		'thread_local_end': [280],
		'thread_local_limit': [288],
		'thread_local_objects': [296],
		'jni_entrypoints': [304],
		'quick_entrypoints': [312],
		'mterp_current_ibase': [1608],
		'mterp_default_ibase': [1616],
		'mterp_alt_ibase': [1624],
		'rosalloc_runs': [1632],
		'thread_local_alloc_stack_top': [1760],
		'thread_local_alloc_stack_end': [1768],
		'held_mutexes': [1776],
		'flip_function': [2336],
		'method_verifier': [2344],
		'thread_local_mark_stack': [2352],
		'async_exception': [2360],
	}],

	'PtrSizedFields': [0x10, {
		'data_': [0],
		'entry_point_from_quick_compiled_code_': [8],
	}],

	'Heap': [0x568, {
		'continuous_spaces_': [0],
		'discontinuous_spaces_': [24],
		'alloc_spaces_': [48],
		'non_moving_space_': [72],
		'rosalloc_space_': [80],
		'dlmalloc_space_': [88],
		'main_space_': [96],
		'large_object_space_': [104],
		'card_table_': [112],
		'rb_table_': [120],
		'mod_union_tables_': [128],
		'remembered_sets_': [152],
		'collector_type_': [176],
		'foreground_collector_type_': [180],
		'background_collector_type_': [184],
		'desired_collector_type_': [188],
		'pending_task_lock_': [192],
		'parallel_gc_threads_': [200],
		'conc_gc_threads_': [208],
		'low_memory_mode_': [216],
		'long_pause_log_threshold_': [224],
		'long_gc_log_threshold_': [232],
		'ignore_max_footprint_': [240],
		'zygote_creation_lock_': [248],
		'zygote_space_': [304],
		'large_object_threshold_': [312],
		'gc_complete_lock_': [320],
		'gc_complete_cond_': [328],
		'thread_flip_lock_': [336],
		'thread_flip_cond_': [344],
		'disable_thread_flip_count_': [352],
		'thread_flip_running_': [360],
		'reference_processor_': [368],
		'task_processor_': [376],
		'collector_type_running_': [384],
		'last_gc_cause_': [388],
		'thread_running_gc_': [392],
		'last_gc_type_': [400],
		'next_gc_type_': [404],
		'capacity_': [408],
		'growth_limit_': [416],
		'max_allowed_footprint_': [424],
		'concurrent_start_bytes_': [432],
		'total_bytes_freed_ever_': [440],
		'total_objects_freed_ever_': [448],
		'num_bytes_allocated_': [456],
		'new_native_bytes_allocated_': [464],
		'old_native_bytes_allocated_': [472],
		'num_bytes_freed_revoke_': [480],
		'current_gc_iteration_': [488],
		'verify_missing_card_marks_': [608],
		'verify_system_weaks_': [609],
		'verify_pre_gc_heap_': [610],
		'verify_pre_sweeping_heap_': [611],
		'verify_post_gc_heap_': [612],
		'verify_mod_union_table_': [613],
		'verify_pre_gc_rosalloc_': [614],
		'verify_pre_sweeping_rosalloc_': [615],
		'verify_post_gc_rosalloc_': [616],
		'gc_stress_mode_': [617],
		'thread_pool_': [624],
		'live_bitmap_': [632],
		'mark_bitmap_': [640],
		'mark_stack_': [648],
		'max_allocation_stack_size_': [656],
		'allocation_stack_': [664],
		'live_stack_': [672],
		'current_allocator_': [680],
		'current_non_moving_allocator_': [684],
		'gc_plan_': [688],
		'bump_pointer_space_': [712],
		'temp_space_': [720],
		'region_space_': [728],
		'min_free_': [736],
		'max_free_': [744],
		'target_utilization_': [752],
		'foreground_heap_growth_multiplier_': [760],
		'total_wait_time_': [768],
		'verify_object_mode_': [776],
		'disable_moving_gc_count_': [784],
		'garbage_collectors_': [792],
		'semi_space_collector_': [816],
		'mark_compact_collector_': [824],
		'concurrent_copying_collector_': [832],
		'is_running_on_memory_tool_': [840],
		'use_tlab_': [841],
		'main_space_backup_': [848],
		'min_interval_homogeneous_space_compaction_by_oom_': [856],
		'last_time_homogeneous_space_compaction_by_oom_': [864],
		'count_delayed_oom_': [872],
		'count_requested_homogeneous_space_compaction_': [880],
		'count_ignored_homogeneous_space_compaction_': [888],
		'count_performed_homogeneous_space_compaction_': [896],
		'concurrent_gc_pending_': [904],
		'pending_collector_transition_': [912],
		'pending_heap_trim_': [920],
		'use_homogeneous_space_compaction_for_oom_': [928],
		'running_collection_is_blocking_': [929],
		'blocking_gc_count_': [936],
		'blocking_gc_time_': [944],
		'last_update_time_gc_count_rate_histograms_': [952],
		'gc_count_last_window_': [960],
		'blocking_gc_count_last_window_': [968],
		'gc_count_rate_histogram_': [976],
		'blocking_gc_count_rate_histogram_': [1112],
		'alloc_tracking_enabled_': [1248],
		'allocation_records_': [1256],
		'backtrace_lock_': [1264],
		'seen_backtrace_count_': [1272],
		'unique_backtrace_count_': [1280],
		'seen_backtraces_': [1288],
		'gc_disabled_for_shutdown_': [1328],
		'boot_image_spaces_': [1336],
		'alloc_listener_': [1360],
		'gc_pause_listener_': [1368],
		'verification_': [1376],
	}],

	'TypeId': [0x4, {
		'descriptor_idx_': [0],
	}],

	'FieldId': [0x8, {
		'class_idx_': [0],
		'type_idx_': [2],
		'name_idx_': [4],
	}],

	'StringId': [0x4, {
		'string_data_off_': [0],
	}],

	'MethodId': [0x8, {
		'class_idx_': [0],
		'proto_idx_': [2],
		'name_idx_': [4],
	}],

	'Field': [0x20, {
		'padding_': [10],
		'declaring_class_': [12],
		'type_': [16],
		'access_flags_': [20],
		'dex_field_index_': [24],
		'offset_': [28],
	}],

	'ContinuousMemMapAllocSpace': [0x68, {
		'live_bitmap_': [80],
		'mark_bitmap_': [88],
		'temp_bitmap_': [96],
	}],

	'MemMapSpace': [0x48, {
		'mem_map_': [64],
	}],

	'RegionSpace': [0x140, {
		'region_lock_': [104],
		'time_': [160],
		'num_regions_': [168],
		'num_non_free_regions_': [176],
		'num_evac_regions_': [184],
		'max_peak_num_non_free_regions_': [192],
		'regions_': [200],
		'non_free_region_index_limit_': [208],
		'current_region_': [216],
		'evac_region_': [224],
		'full_region_': [232],
		'mark_bitmap_': [312],
	}],

	'ContinuousSpace': [0x40, {
		'begin_': [40],
		'end_': [48],
		'limit_': [56],
	}],

	'AllocSpace': [0x8, {
		'_vptr$AllocSpace': [0],
	}],

	'ImageSpace': [0x78, {
		'live_bitmap_': [72],
		'oat_file_': [80],
		'oat_file_non_owned_': [88],
		'image_location_': [96],
	}],

	'MallocSpace': [0xc8, {
		'recent_freed_objects_': [104],
		'recent_free_pos_': [104],
		'lock_': [112],
		'growth_limit_': [168],
		'can_move_objects_': [176],
		'starting_size_': [184],
		'initial_size_': [192],
	}],

	'Region': [0x50, {
		'idx_': [0],
		'begin_': [8],
		'top_': [16],
		'end_': [24],
		'state_': [32],
		'type_': [33],
		'objects_allocated_': [40],
		'alloc_time_': [48],
		'live_bytes_': [56],
		'is_newly_allocated_': [64],
		'is_a_tlab_': [65],
		'thread_': [72],
	}],

	# MANUALLY ADDED - Based on other offset files
	# and AndroidXRef for Android 9.0.0_r3, /art/runtime/dex_file.h
	'DexFile': [0xb0, {
		'_vptr$DexFile': [0],
		'begin_': [8],
		'size_': [16],
		'data_begin_': [24],
		'data_size_': [32],
		'location_': [40],
		'location_checksum_': [64],
		'header_': [72],
		'string_ids_': [80],
		'type_ids_': [88],
		'field_ids_': [96],
		'method_ids_': [104],
		'proto_ids_': [112],
		'class_defs_': [120],
		'method_handles_': [128],
		'num_method_handles_': [136],
		'call_site_ids_': [144],
		'oat_dex_file_': [152],
		'container_': [160],
		'is_compact_dex_': [168],
		'is_platform_dex_': [169],
	}],

    'SpaceBitmap':[0x28,{
        'mem_map_' : [0],
        'bitmap_begin_' :[8],
        'bitmap_size_':[16],
        'heap_begin_': [24],
        'name_': [32],
    }],

}