# -*- coding: utf-8 -*-
"""
    @credit: Aisha Ali-Gombe (aaligombe@towson.edu)
    @contributors: Alexandre Blanchon, Arthur Belleville, Corentin Jeudy

    Brief: artTypes offsets - Android 8.1 (64 bits)
"""

types = {
	'Thread': [0x9e0, {
		'tls32_': [0],
		'tls64_': [72],
		'tlsPtr_': [136],
		'wait_mutex_': [2448],
		'wait_cond_': [2456],
		'wait_monitor_': [2464],
		'debug_disallow_read_barrier_': [2472],
		'poison_object_cookie_': [2480],
		'checkpoint_overflow_': [2488],
		'custom_tls_': [2512],
		'can_call_into_java_': [2520],
	}],

	'ArtMethod': [0x30, {
		'declaring_class_': [0],
		'access_flags_': [4],
		'dex_code_item_offset_': [8],
		'dex_method_index_': [12],
		'method_index_': [16],
		'hotness_count_': [18],
		'ptr_sized_fields_': [24],
	}],

	'ArtField': [0x10, {
		'declaring_class_': [0],
		'access_flags_': [4],
		'field_dex_idx_': [8],
		'offset_': [12],
	}],

	'IRTSegmentState': [0x4, {
		'top_index': [0],
	}],

	'IndirectReferenceTable': [0x38, {
		'segment_state_': [0],
		'table_mem_map_': [8],
		'table_': [16],
		'kind_': [24],
		'max_entries_': [32],
		'current_num_holes_': [40],
		'last_known_previous_state_': [48],
		'resizable_': [52],
	}],

	'IrtEntry': [0x10, {
		'serial_': [0],
		'references_': [4],
	}],

	'GcRoot<art::mirror::Object>': [0x4, {
		'root_': [0],
	}],

	'Monitor': [0x98, {
		'monitor_lock_': [0],
		'monitor_contenders_': [64],
		'num_waiters_': [88],
		'owner_': [96],
		'lock_count_': [104],
		'obj_': [108],
		'wait_set_': [112],
		'hash_code_': [120],
		'locking_method_': [128],
		'locking_dex_pc_': [136],
		'monitor_id_': [140],
		'next_free_': [144],
	}],

	'Runtime': [0x558, {
		'callee_save_methods_': [0],
		'pre_allocated_OutOfMemoryError_': [32],
		'pre_allocated_NoClassDefFoundError_': [36],
		'resolution_method_': [40],
		'imt_conflict_method_': [48],
		'imt_unimplemented_method_': [56],
		'sentinel_': [64],
		'instruction_set_': [68],
		'callee_save_method_frame_infos_': [72],
		'compiler_callbacks_': [120],
		'is_zygote_': [128],
		'must_relocate_': [129],
		'is_concurrent_gc_enabled_': [130],
		'is_explicit_gc_disabled_': [131],
		'dex2oat_enabled_': [132],
		'image_dex2oat_enabled_': [133],
		'compiler_executable_': [136],
		'patchoat_executable_': [160],
		'compiler_options_': [184],
		'image_compiler_options_': [208],
		'image_location_': [232],
		'boot_class_path_string_': [256],
		'class_path_string_': [280],
		'properties_': [304],
		'agents_': [328],
		'plugins_': [352],
		'default_stack_size_': [376],
		'heap_': [384],
		'jit_arena_pool_': [392],
		'arena_pool_': [400],
		'low_4gb_arena_pool_': [408],
		'linear_alloc_': [416],
		'max_spins_before_thin_lock_inflation_': [424],
		'monitor_list_': [432],
		'monitor_pool_': [440],
		'thread_list_': [448],
		'intern_table_': [456],
		'class_linker_': [464],
		'signal_catcher_': [472],
		'use_tombstoned_traces_': [480],
		'stack_trace_file_': [488],
		'java_vm_': [512],
		'jit_': [520],
		'jit_options_': [528],
		'fault_message_lock_': [536],
		'fault_message_': [600],
		'threads_being_born_': [624],
		'shutdown_cond_': [632],
		'shutting_down_': [640],
		'shutting_down_started_': [641],
		'started_': [642],
		'finished_starting_': [643],
		'vfprintf_': [648],
		'exit_': [656],
		'abort_': [664],
		'stats_enabled_': [672],
		'stats_': [676],
		'is_running_on_memory_tool_': [732],
		'trace_config_': [736],
		'instrumentation_': [744],
		'main_thread_group_': [1120],
		'system_thread_group_': [1128],
		'system_class_loader_': [1136],
		'dump_gc_performance_on_shutdown_': [1144],
		'preinitialization_transaction_': [1152],
		'verify_': [1160],
		'allow_dex_file_fallback_': [1161],
		'cpu_abilist_': [1168],
		'target_sdk_version_': [1192],
		'implicit_null_checks_': [1196],
		'implicit_so_checks_': [1197],
		'implicit_suspend_checks_': [1198],
		'no_sig_chain_': [1199],
		'force_native_bridge_': [1200],
		'is_native_bridge_loaded_': [1201],
		'is_native_debuggable_': [1202],
		'is_java_debuggable_': [1203],
		'zygote_max_failed_boots_': [1204],
		'experimental_flags_': [1208],
		'fingerprint_': [1216],
		'oat_file_manager_': [1240],
		'is_low_memory_mode_': [1248],
		'madvise_random_access_': [1249],
		'safe_mode_': [1250],
		'dump_native_stack_on_sig_quit_': [1251],
		'pruned_dalvik_cache_': [1252],
		'process_state_': [1256],
		'zygote_no_threads_': [1260],
		'env_snapshot_': [1264],
		'system_weak_holders_': [1296],
		'callbacks_': [1320],
		'deoptimization_counts_': [1328],
		'protected_fault_page_': [1360],
	}],

	'ThreadList': [0x20c8, {
		'allocated_ids_': [0],
		'list_': [8192],
		'suspend_all_count_': [8216],
		'debug_suspend_all_count_': [8220],
		'unregistering_count_': [8224],
		'suspend_all_historam_': [8232],
		'long_suspend_': [8368],
		'shut_down_': [8369],
		'thread_suspend_timeout_ns_': [8376],
		'empty_checkpoint_barrier_': [8384],
	}],

	'JavaVMExt': [0xf8, {
		'runtime_': [8],
		'check_jni_abort_hook_': [16],
		'check_jni_abort_hook_data_': [24],
		'check_jni_': [32],
		'force_copy_': [33],
		'tracing_enabled_': [34],
		'trace_': [40],
		'globals_': [64],
		'libraries_': [120],
		'unchecked_functions_': [128],
		'weak_globals_': [136],
		'allow_accessing_weak_globals_': [192],
		'weak_globals_add_condition_': [200],
		'env_hooks_': [224],
	}],

	'DexFile': [0xa0, {
		'_vptr$DexFile': [0],
		'begin_': [8],
		'size_': [16],
		'location_': [24],
		'location_checksum_': [48],
		'mem_map_': [56],
		'header_': [64],
		'string_ids_': [72],
		'type_ids_': [80],
		'field_ids_': [88],
		'method_ids_': [96],
		'proto_ids_': [104],
		'class_defs_': [112],
		'method_handles_': [120],
		'num_method_handles_': [128],
		'call_site_ids_': [136],
		'num_call_site_ids_': [144],
		'oat_dex_file_': [152],
	}],

	'OatFile': [0x100, {
		'_vptr$OatFile': [0],
		'location_': [8],
		'vdex_': [32],
		'begin_': [40],
		'end_': [48],
		'bss_begin_': [56],
		'bss_end_': [64],
		'bss_methods_': [72],
		'bss_roots_': [80],
		'is_executable_': [88],
		'oat_dex_files_storage_': [96],
		'oat_dex_files_': [120],
		'secondary_lookup_lock_': [144],
		'secondary_oat_dex_files_': [208],
		'string_cache_': [232],
	}],

	'Class': [0x78, {
		'class_loader_': [8],
		'component_type_': [12],
		'dex_cache_': [16],
		'ext_data_': [20],
		'iftable_': [24],
		'name_': [28],
		'super_class_': [32],
		'vtable_': [36],
		'ifields_': [40],
		'methods_': [48],
		'sfields_': [56],
		'access_flags_': [64],
		'class_flags_': [68],
		'class_size_': [72],
		'clinit_thread_id_': [76],
		'dex_class_def_idx_': [80],
		'dex_type_idx_': [84],
		'num_reference_instance_fields_': [88],
		'num_reference_static_fields_': [92],
		'object_size_': [96],
		'object_size_alloc_fast_path_': [100],
		'primitive_type_': [104],
		'reference_instance_offsets_': [108],
		'status_': [112],
		'copied_methods_offset_': [116],
		'virtual_methods_offset_': [118],
	}],

	'Object': [0x8, {
		'klass_': [0],
		'monitor_': [4],
	}],

	'CompressedReference<art::mirror::Object>': [0x4, {
	}],

	'ObjectReference<false, art::mirror::Object>': [0x4, {
		'reference_': [0],
	}],

	'String': [0x10, {
		'count_': [8],
		'hash_code_': [12],
		'': [16],
	}],

	'DexCache': [0x5c, {
		'location_': [8],
		'num_resolved_call_sites_': [12],
		'dex_file_': [16],
		'resolved_call_sites_': [24],
		'resolved_fields_': [32],
		'resolved_method_types_': [40],
		'resolved_methods_': [48],
		'resolved_types_': [56],
		'strings_': [64],
		'num_resolved_fields_': [72],
		'num_resolved_method_types_': [76],
		'num_resolved_methods_': [80],
		'num_resolved_types_': [84],
		'num_strings_': [88],
	}],

	'tls_32bit_sized_values': [0x48, {
		'state_and_flags': [0],
		'suspend_count': [4],
		'debug_suspend_count': [8],
		'thin_lock_thread_id': [12],
		'tid': [16],
		'daemon': [20],
		'throwing_OutOfMemoryError': [24],
		'no_thread_suspension': [28],
		'thread_exit_check_count': [32],
		'handling_signal_': [36],
		'is_transitioning_to_runnable': [40],
		'ready_for_debug_invoke': [44],
		'debug_method_entry_': [48],
		'is_gc_marking': [52],
		'interrupted': [56],
		'weak_ref_access_enabled': [60],
		'disable_thread_flip_count': [64],
		'user_code_suspend_count': [68],
		'as_struct': [0],
		'as_atomic_int': [0],
		'as_int': [0],
	}],

	'tls_64bit_sized_values': [0x40, {
		'trace_clock_base': [0],
		'stats': [8],
	}],

	'tls_ptr_sized_values': [0x908, {
		'card_table': [0],
		'exception': [8],
		'stack_end': [16],
		'managed_stack': [24],
		'suspend_trigger': [48],
		'jni_env': [56],
		'tmp_jni_env': [64],
		'self': [72],
		'opeer': [80],
		'jpeer': [88],
		'stack_begin': [96],
		'stack_size': [104],
		'deps_or_stack_trace_sample': [112],
		'wait_next': [120],
		'monitor_enter_object': [128],
		'top_handle_scope': [136],
		'class_loader_override': [144],
		'long_jump_context': [152],
		'instrumentation_stack': [160],
		'debug_invoke_req': [168],
		'single_step_control': [176],
		'stacked_shadow_frame_record': [184],
		'deoptimization_context_stack': [192],
		'frame_id_to_shadow_frame': [200],
		'name': [208],
		'pthread_self': [216],
		'last_no_thread_suspension_cause': [224],
		'checkpoint_function': [232],
		'active_suspend_barriers': [240],
		'thread_local_start': [264],
		'thread_local_pos': [272],
		'thread_local_end': [280],
		'thread_local_limit': [288],
		'thread_local_objects': [296],
		'jni_entrypoints': [304],
		'quick_entrypoints': [312],
		'mterp_current_ibase': [1600],
		'mterp_default_ibase': [1608],
		'mterp_alt_ibase': [1616],
		'rosalloc_runs': [1624],
		'thread_local_alloc_stack_top': [1752],
		'thread_local_alloc_stack_end': [1760],
		'held_mutexes': [1768],
		'flip_function': [2288],
		'method_verifier': [2296],
		'thread_local_mark_stack': [2304],
	}],

	'PtrSizedFields': [0x18, {
		'dex_cache_resolved_methods_': [0],
		'data_': [8],
		'entry_point_from_quick_compiled_code_': [16],
	}],

	'ProtoId': [0xc, {
		'shorty_idx_': [0],
		'return_type_idx_': [4],
		'pad_': [6],
		'parameters_off_': [8],
	}],

	'ClassDef': [0x20, {
		'class_idx_': [0],
		'pad1_': [2],
		'access_flags_': [4],
		'superclass_idx_': [8],
		'pad2_': [10],
		'interfaces_off_': [12],
		'source_file_idx_': [16],
		'annotations_off_': [20],
		'class_data_off_': [24],
		'static_values_off_': [28],
	}],

	'Heap': [0x590, {
		'continuous_spaces_': [0],
		'discontinuous_spaces_': [24],
		'alloc_spaces_': [48],
		'non_moving_space_': [72],
		'rosalloc_space_': [80],
		'dlmalloc_space_': [88],
		'main_space_': [96],
		'large_object_space_': [104],
		'card_table_': [112],
		'rb_table_': [120],
		'mod_union_tables_': [128],
		'remembered_sets_': [152],
		'collector_type_': [176],
		'foreground_collector_type_': [180],
		'background_collector_type_': [184],
		'desired_collector_type_': [188],
		'pending_task_lock_': [192],
		'parallel_gc_threads_': [200],
		'conc_gc_threads_': [208],
		'low_memory_mode_': [216],
		'long_pause_log_threshold_': [224],
		'long_gc_log_threshold_': [232],
		'ignore_max_footprint_': [240],
		'zygote_creation_lock_': [248],
		'zygote_space_': [312],
		'large_object_threshold_': [320],
		'gc_complete_lock_': [328],
		'gc_complete_cond_': [336],
		'thread_flip_lock_': [344],
		'thread_flip_cond_': [352],
		'disable_thread_flip_count_': [360],
		'thread_flip_running_': [368],
		'reference_processor_': [376],
		'task_processor_': [384],
		'collector_type_running_': [392],
		'last_gc_cause_': [396],
		'thread_running_gc_': [400],
		'last_gc_type_': [408],
		'next_gc_type_': [412],
		'capacity_': [416],
		'growth_limit_': [424],
		'max_allowed_footprint_': [432],
		'concurrent_start_bytes_': [440],
		'total_bytes_freed_ever_': [448],
		'total_objects_freed_ever_': [456],
		'num_bytes_allocated_': [464],
		'new_native_bytes_allocated_': [472],
		'old_native_bytes_allocated_': [480],
		'native_blocking_gc_lock_': [488],
		'native_blocking_gc_cond_': [496],
		'native_blocking_gc_is_assigned_': [504],
		'native_blocking_gc_in_progress_': [505],
		'native_blocking_gcs_finished_': [508],
		'num_bytes_freed_revoke_': [512],
		'current_gc_iteration_': [520],
		'verify_missing_card_marks_': [640],
		'verify_system_weaks_': [641],
		'verify_pre_gc_heap_': [642],
		'verify_pre_sweeping_heap_': [643],
		'verify_post_gc_heap_': [644],
		'verify_mod_union_table_': [645],
		'verify_pre_gc_rosalloc_': [646],
		'verify_pre_sweeping_rosalloc_': [647],
		'verify_post_gc_rosalloc_': [648],
		'gc_stress_mode_': [649],
		'thread_pool_': [656],
		'allocation_rate_': [664],
		'live_bitmap_': [672],
		'mark_bitmap_': [680],
		'mark_stack_': [688],
		'max_allocation_stack_size_': [696],
		'allocation_stack_': [704],
		'live_stack_': [712],
		'current_allocator_': [720],
		'current_non_moving_allocator_': [724],
		'gc_plan_': [728],
		'bump_pointer_space_': [752],
		'temp_space_': [760],
		'region_space_': [768],
		'min_free_': [776],
		'max_free_': [784],
		'target_utilization_': [792],
		'foreground_heap_growth_multiplier_': [800],
		'total_wait_time_': [808],
		'verify_object_mode_': [816],
		'disable_moving_gc_count_': [824],
		'garbage_collectors_': [832],
		'semi_space_collector_': [856],
		'mark_compact_collector_': [864],
		'concurrent_copying_collector_': [872],
		'is_running_on_memory_tool_': [880],
		'use_tlab_': [881],
		'main_space_backup_': [888],
		'min_interval_homogeneous_space_compaction_by_oom_': [896],
		'last_time_homogeneous_space_compaction_by_oom_': [904],
		'count_delayed_oom_': [912],
		'count_requested_homogeneous_space_compaction_': [920],
		'count_ignored_homogeneous_space_compaction_': [928],
		'count_performed_homogeneous_space_compaction_': [936],
		'concurrent_gc_pending_': [944],
		'pending_collector_transition_': [952],
		'pending_heap_trim_': [960],
		'use_homogeneous_space_compaction_for_oom_': [968],
		'running_collection_is_blocking_': [969],
		'blocking_gc_count_': [976],
		'blocking_gc_time_': [984],
		'last_update_time_gc_count_rate_histograms_': [992],
		'gc_count_last_window_': [1000],
		'blocking_gc_count_last_window_': [1008],
		'gc_count_rate_histogram_': [1016],
		'blocking_gc_count_rate_histogram_': [1152],
		'alloc_tracking_enabled_': [1288],
		'allocation_records_': [1296],
		'backtrace_lock_': [1304],
		'seen_backtrace_count_': [1312],
		'unique_backtrace_count_': [1320],
		'seen_backtraces_': [1328],
		'gc_disabled_for_shutdown_': [1368],
		'boot_image_spaces_': [1376],
		'alloc_listener_': [1400],
		'gc_pause_listener_': [1408],
		'verification_': [1416],
	}],

	'TypeId': [0x4, {
		'descriptor_idx_': [0],
	}],

	'FieldId': [0x8, {
		'class_idx_': [0],
		'type_idx_': [2],
		'name_idx_': [4],
	}],

	'StringId': [0x4, {
		'string_data_off_': [0],
	}],

	'MethodId': [0x8, {
		'class_idx_': [0],
		'proto_idx_': [2],
		'name_idx_': [4],
	}],

	'Field': [0x20, {
		'padding_': [10],
		'declaring_class_': [12],
		'type_': [16],
		'access_flags_': [20],
		'dex_field_index_': [24],
		'offset_': [28],
	}],

	'ContinuousMemMapAllocSpace': [0x68, {
		'live_bitmap_': [80],
		'mark_bitmap_': [88],
		'temp_bitmap_': [96],
	}],

	'MemMapSpace': [0x48, {
		'mem_map_': [64],
	}],

	'RegionSpace': [0x138, {
		'region_lock_': [104],
		'time_': [168],
		'num_regions_': [176],
		'num_non_free_regions_': [184],
		'regions_': [192],
		'non_free_region_index_limit_': [200],
		'current_region_': [208],
		'evac_region_': [216],
		'full_region_': [224],
		'mark_bitmap_': [304],
	}],

	'ContinuousSpace': [0x40, {
		'begin_': [40],
		'end_': [48],
		'limit_': [56],
	}],

	'AllocSpace': [0x8, {
		'_vptr$AllocSpace': [0],
	}],

	'ImageSpace': [0x78, {
		'live_bitmap_': [72],
		'oat_file_': [80],
		'oat_file_non_owned_': [88],
		'image_location_': [96],
	}],

	'MallocSpace': [0xd0, {
		'recent_freed_objects_': [104],
		'recent_free_pos_': [104],
		'lock_': [112],
		'growth_limit_': [176],
		'can_move_objects_': [184],
		'starting_size_': [192],
		'initial_size_': [200],
	}],

	'Region': [0x50, {
		'idx_': [0],
		'begin_': [8],
		'top_': [16],
		'end_': [24],
		'state_': [32],
		'type_': [33],
		'objects_allocated_': [40],
		'alloc_time_': [48],
		'live_bytes_': [56],
		'is_newly_allocated_': [64],
		'is_a_tlab_': [65],
		'thread_': [72],
	}],

    'SpaceBitmap':[0x28,{
        'mem_map_' : [0],
        'bitmap_begin_' :[8],
        'bitmap_size_':[16],
        'heap_begin_': [24],
        'name_': [32],
    }],

}