# -*- coding: utf-8 -*-
"""
    @credit: Aisha Ali-Gombe (aaligombe@towson.edu)
    @contributors: Alexandre Blanchon, Arthur Belleville, Corentin Jeudy

    Brief: artTypes offsets - Android 9 (32 bits)
"""

types = {
	'IndirectReferenceTable': [0x20, {
		'segment_state_': [0],
		'table_mem_map_': [4],
		'table_': [8],
		'kind_': [12],
		'max_entries_': [16],
		'current_num_holes_': [20],
		'last_known_previous_state_': [24],
		'resizable_': [28],
	}],

	'IRTSegmentState': [0x4, {
		'top_index': [0],
	}],

	'IrtEntry': [0x10, {
		'serial_': [0],
		'references_': [4],
	}],

	'GcRoot<art::mirror::Object>': [0x4, {
		'root_': [0],
	}],

	'Thread': [0x550, {
		'tls32_': [0],
		'tls64_': [72],
		'tlsPtr_': [136],
		'wait_mutex_': [1320],
		'wait_cond_': [1324],
		'wait_monitor_': [1328],
		'debug_disallow_read_barrier_': [1332],
		'poison_object_cookie_': [1336],
		'checkpoint_overflow_': [1340],
		'custom_tls_': [1352],
		'can_call_into_java_': [1356],
	}],

	'ArtMethod': [0x1c, {
		'declaring_class_': [0],
		'access_flags_': [4],
		'dex_code_item_offset_': [8],
		'dex_method_index_': [12],
		'method_index_': [16],
		'hotness_count_': [18],
		'ptr_sized_fields_': [20],
	}],

	'Monitor': [0x60, {
		'monitor_lock_': [0],
		'monitor_contenders_': [40],
		'num_waiters_': [56],
		'owner_': [60],
		'lock_count_': [64],
		'obj_': [68],
		'wait_set_': [72],
		'hash_code_': [76],
		'locking_method_': [80],
		'locking_dex_pc_': [84],
		'monitor_id_': [88],
	}],

	'ArtField': [0x10, {
		'declaring_class_': [0],
		'access_flags_': [4],
		'field_dex_idx_': [8],
		'offset_': [12],
	}],

	'Runtime': [0x3d0, {
		'callee_save_methods_': [0],
		'pre_allocated_OutOfMemoryError_': [48],
		'pre_allocated_NoClassDefFoundError_': [52],
		'resolution_method_': [56],
		'imt_conflict_method_': [60],
		'imt_unimplemented_method_': [64],
		'sentinel_': [68],
		'instruction_set_': [72],
		'callee_save_method_frame_infos_': [76],
		'compiler_callbacks_': [148],
		'is_zygote_': [152],
		'must_relocate_': [153],
		'is_concurrent_gc_enabled_': [154],
		'is_explicit_gc_disabled_': [155],
		'dex2oat_enabled_': [156],
		'image_dex2oat_enabled_': [157],
		'compiler_executable_': [160],
		'patchoat_executable_': [172],
		'compiler_options_': [184],
		'image_compiler_options_': [196],
		'image_location_': [208],
		'boot_class_path_string_': [220],
		'class_path_string_': [232],
		'properties_': [244],
		'agent_specs_': [256],
		'agents_': [268],
		'plugins_': [280],
		'default_stack_size_': [292],
		'heap_': [296],
		'jit_arena_pool_': [300],
		'arena_pool_': [304],
		'low_4gb_arena_pool_': [308],
		'linear_alloc_': [312],
		'max_spins_before_thin_lock_inflation_': [316],
		'monitor_list_': [320],
		'monitor_pool_': [324],
		'thread_list_': [328],
		'intern_table_': [332],
		'class_linker_': [336],
		'signal_catcher_': [340],
		'use_tombstoned_traces_': [344],
		'stack_trace_file_': [348],
		'java_vm_': [360],
		'jit_': [364],
		'jit_options_': [368],
		'fault_message_lock_': [376],
		'fault_message_': [416],
		'threads_being_born_': [428],
		'shutdown_cond_': [432],
		'shutting_down_': [436],
		'shutting_down_started_': [437],
		'started_': [438],
		'finished_starting_': [439],
		'vfprintf_': [440],
		'exit_': [444],
		'abort_': [448],
		'stats_enabled_': [452],
		'stats_': [456],
		'is_running_on_memory_tool_': [512],
		'trace_config_': [516],
		'instrumentation_': [520],
		'main_thread_group_': [752],
		'system_thread_group_': [756],
		'system_class_loader_': [760],
		'dump_gc_performance_on_shutdown_': [764],
		'preinitialization_transactions_': [768],
		'verify_': [780],
		'allow_dex_file_fallback_': [781],
		'cpu_abilist_': [784],
		'target_sdk_version_': [796],
		'implicit_null_checks_': [800],
		'implicit_so_checks_': [801],
		'implicit_suspend_checks_': [802],
		'no_sig_chain_': [803],
		'force_native_bridge_': [804],
		'is_native_bridge_loaded_': [805],
		'is_native_debuggable_': [806],
		'async_exceptions_thrown_': [807],
		'is_java_debuggable_': [808],
		'zygote_max_failed_boots_': [812],
		'experimental_flags_': [816],
		'fingerprint_': [820],
		'oat_file_manager_': [832],
		'is_low_memory_mode_': [836],
		'madvise_random_access_': [837],
		'safe_mode_': [838],
		'hidden_api_policy_': [840],
		'hidden_api_exemptions_': [844],
		'pending_hidden_api_warning_': [856],
		'dedupe_hidden_api_warnings_': [857],
		'always_set_hidden_api_warning_flag_': [858],
		'hidden_api_access_event_log_rate_': [860],
		'process_package_name_': [864],
		'dump_native_stack_on_sig_quit_': [876],
		'pruned_dalvik_cache_': [877],
		'process_state_': [880],
		'zygote_no_threads_': [884],
		'jdwp_options_': [888],
		'jdwp_provider_': [900],
		'env_snapshot_': [904],
		'system_weak_holders_': [920],
		'callbacks_': [932],
		'deoptimization_counts_': [936],
		'protected_fault_page_': [968],
	}],

	'ThreadList': [0x208c, {
		'allocated_ids_': [0],
		'list_': [8192],
		'suspend_all_count_': [8204],
		'debug_suspend_all_count_': [8208],
		'unregistering_count_': [8212],
		'suspend_all_historam_': [8216],
		'long_suspend_': [8316],
		'shut_down_': [8317],
		'thread_suspend_timeout_ns_': [8320],
		'empty_checkpoint_barrier_': [8328],
	}],

	'JavaVMExt': [0x90, {
		'runtime_': [4],
		'check_jni_abort_hook_': [8],
		'check_jni_abort_hook_data_': [12],
		'check_jni_': [16],
		'force_copy_': [17],
		'tracing_enabled_': [18],
		'trace_': [20],
		'globals_': [32],
		'libraries_': [64],
		'unchecked_functions_': [68],
		'weak_globals_': [72],
		'allow_accessing_weak_globals_': [104],
		'weak_globals_add_condition_': [108],
		'env_hooks_': [124],
		'enable_allocation_tracking_delta_': [136],
		'allocation_tracking_enabled_': [140],
		'old_allocation_tracking_state_': [141],
	}],

	'OatFile': [0x98, {
		'_vptr$OatFile': [0],
		'location_': [4],
		'vdex_': [16],
		'begin_': [20],
		'end_': [24],
		'bss_begin_': [28],
		'bss_end_': [32],
		'bss_methods_': [36],
		'bss_roots_': [40],
		'is_executable_': [44],
		'vdex_begin_': [48],
		'vdex_end_': [52],
		'oat_dex_files_storage_': [56],
		'oat_dex_files_': [68],
		'secondary_lookup_lock_': [80],
		'secondary_oat_dex_files_': [120],
		'string_cache_': [132],
		'uncompressed_dex_files_': [144],
	}],

	'ProtoId': [0xc, {
		'shorty_idx_': [0],
		'return_type_idx_': [4],
		'pad_': [6],
		'parameters_off_': [8],
	}],

	'ClassDef': [0x20, {
		'class_idx_': [0],
		'pad1_': [2],
		'access_flags_': [4],
		'superclass_idx_': [8],
		'pad2_': [10],
		'interfaces_off_': [12],
		'source_file_idx_': [16],
		'annotations_off_': [20],
		'class_data_off_': [24],
		'static_values_off_': [28],
	}],

	'CompressedReference<art::mirror::Object>': [0x4, {
	}],

	'ObjectReference<false, art::mirror::Object>': [0x4, {
		'reference_': [0],
	}],

	'Object': [0x8, {
		'klass_': [0],
		'monitor_': [4],
	}],

	'Class': [0x78, {
		'class_loader_': [8],
		'component_type_': [12],
		'dex_cache_': [16],
		'ext_data_': [20],
		'iftable_': [24],
		'name_': [28],
		'super_class_': [32],
		'vtable_': [36],
		'ifields_': [40],
		'methods_': [48],
		'sfields_': [56],
		'access_flags_': [64],
		'class_flags_': [68],
		'class_size_': [72],
		'clinit_thread_id_': [76],
		'dex_class_def_idx_': [80],
		'dex_type_idx_': [84],
		'num_reference_instance_fields_': [88],
		'num_reference_static_fields_': [92],
		'object_size_': [96],
		'object_size_alloc_fast_path_': [100],
		'primitive_type_': [104],
		'reference_instance_offsets_': [108],
		'status_': [112],
		'copied_methods_offset_': [116],
		'virtual_methods_offset_': [118],
	}],

	'DexCache': [0x5c, {
		'location_': [8],
		'num_resolved_call_sites_': [12],
		'dex_file_': [16],
		'resolved_call_sites_': [24],
		'resolved_fields_': [32],
		'resolved_method_types_': [40],
		'resolved_methods_': [48],
		'resolved_types_': [56],
		'strings_': [64],
		'num_resolved_fields_': [72],
		'num_resolved_method_types_': [76],
		'num_resolved_methods_': [80],
		'num_resolved_types_': [84],
		'num_strings_': [88],
	}],

	'String': [0x10, {
		'count_': [8],
		'hash_code_': [12],
		'': [16],
	}],

	'tls_32bit_sized_values': [0x48, {
		'state_and_flags': [0],
		'suspend_count': [4],
		'debug_suspend_count': [8],
		'thin_lock_thread_id': [12],
		'tid': [16],
		'daemon': [20],
		'throwing_OutOfMemoryError': [24],
		'no_thread_suspension': [28],
		'thread_exit_check_count': [32],
		'handling_signal_': [36],
		'is_transitioning_to_runnable': [40],
		'ready_for_debug_invoke': [44],
		'debug_method_entry_': [48],
		'is_gc_marking': [52],
		'interrupted': [56],
		'weak_ref_access_enabled': [60],
		'disable_thread_flip_count': [64],
		'user_code_suspend_count': [68],
		'as_struct': [0],
		'as_atomic_int': [0],
		'as_int': [0],
	}],

	'tls_64bit_sized_values': [0x40, {
		'trace_clock_base': [0],
		'stats': [8],
	}],

	'tls_ptr_sized_values': [0x4a0, {
		'card_table': [0],
		'exception': [4],
		'stack_end': [8],
		'managed_stack': [12],
		'suspend_trigger': [24],
		'jni_env': [28],
		'tmp_jni_env': [32],
		'self': [36],
		'opeer': [40],
		'jpeer': [44],
		'stack_begin': [48],
		'stack_size': [52],
		'deps_or_stack_trace_sample': [56],
		'wait_next': [60],
		'monitor_enter_object': [64],
		'top_handle_scope': [68],
		'class_loader_override': [72],
		'long_jump_context': [76],
		'instrumentation_stack': [80],
		'debug_invoke_req': [84],
		'single_step_control': [88],
		'stacked_shadow_frame_record': [92],
		'deoptimization_context_stack': [96],
		'frame_id_to_shadow_frame': [100],
		'name': [104],
		'pthread_self': [108],
		'last_no_thread_suspension_cause': [112],
		'checkpoint_function': [116],
		'active_suspend_barriers': [120],
		'thread_local_start': [132],
		'thread_local_pos': [136],
		'thread_local_end': [140],
		'thread_local_limit': [144],
		'thread_local_objects': [148],
		'jni_entrypoints': [152],
		'quick_entrypoints': [156],
		'mterp_current_ibase': [804],
		'mterp_default_ibase': [808],
		'mterp_alt_ibase': [812],
		'rosalloc_runs': [816],
		'thread_local_alloc_stack_top': [880],
		'thread_local_alloc_stack_end': [884],
		'held_mutexes': [888],
		'flip_function': [1168],
		'method_verifier': [1172],
		'thread_local_mark_stack': [1176],
		'async_exception': [1180],
	}],

	'PtrSizedFields': [0x8, {
		'data_': [0],
		'entry_point_from_quick_compiled_code_': [4],
	}],

	'Heap': [0x378, {
		'continuous_spaces_': [0],
		'discontinuous_spaces_': [12],
		'alloc_spaces_': [24],
		'non_moving_space_': [36],
		'rosalloc_space_': [40],
		'dlmalloc_space_': [44],
		'main_space_': [48],
		'large_object_space_': [52],
		'card_table_': [56],
		'rb_table_': [60],
		'mod_union_tables_': [64],
		'remembered_sets_': [76],
		'collector_type_': [88],
		'foreground_collector_type_': [92],
		'background_collector_type_': [96],
		'desired_collector_type_': [100],
		'pending_task_lock_': [104],
		'parallel_gc_threads_': [108],
		'conc_gc_threads_': [112],
		'low_memory_mode_': [116],
		'long_pause_log_threshold_': [120],
		'long_gc_log_threshold_': [124],
		'ignore_max_footprint_': [128],
		'zygote_creation_lock_': [136],
		'zygote_space_': [176],
		'large_object_threshold_': [180],
		'gc_complete_lock_': [184],
		'gc_complete_cond_': [188],
		'thread_flip_lock_': [192],
		'thread_flip_cond_': [196],
		'disable_thread_flip_count_': [200],
		'thread_flip_running_': [204],
		'reference_processor_': [208],
		'task_processor_': [212],
		'collector_type_running_': [216],
		'last_gc_cause_': [220],
		'thread_running_gc_': [224],
		'last_gc_type_': [228],
		'next_gc_type_': [232],
		'capacity_': [236],
		'growth_limit_': [240],
		'max_allowed_footprint_': [244],
		'concurrent_start_bytes_': [248],
		'total_bytes_freed_ever_': [252],
		'total_objects_freed_ever_': [260],
		'num_bytes_allocated_': [268],
		'new_native_bytes_allocated_': [272],
		'old_native_bytes_allocated_': [276],
		'num_bytes_freed_revoke_': [280],
		'current_gc_iteration_': [284],
		'verify_missing_card_marks_': [376],
		'verify_system_weaks_': [377],
		'verify_pre_gc_heap_': [378],
		'verify_pre_sweeping_heap_': [379],
		'verify_post_gc_heap_': [380],
		'verify_mod_union_table_': [381],
		'verify_pre_gc_rosalloc_': [382],
		'verify_pre_sweeping_rosalloc_': [383],
		'verify_post_gc_rosalloc_': [384],
		'gc_stress_mode_': [385],
		'thread_pool_': [388],
		'live_bitmap_': [392],
		'mark_bitmap_': [396],
		'mark_stack_': [400],
		'max_allocation_stack_size_': [404],
		'allocation_stack_': [408],
		'live_stack_': [412],
		'current_allocator_': [416],
		'current_non_moving_allocator_': [420],
		'gc_plan_': [424],
		'bump_pointer_space_': [436],
		'temp_space_': [440],
		'region_space_': [444],
		'min_free_': [448],
		'max_free_': [452],
		'target_utilization_': [456],
		'foreground_heap_growth_multiplier_': [464],
		'total_wait_time_': [472],
		'verify_object_mode_': [480],
		'disable_moving_gc_count_': [484],
		'garbage_collectors_': [488],
		'semi_space_collector_': [500],
		'mark_compact_collector_': [504],
		'concurrent_copying_collector_': [508],
		'is_running_on_memory_tool_': [512],
		'use_tlab_': [513],
		'main_space_backup_': [516],
		'min_interval_homogeneous_space_compaction_by_oom_': [520],
		'last_time_homogeneous_space_compaction_by_oom_': [528],
		'count_delayed_oom_': [536],
		'count_requested_homogeneous_space_compaction_': [540],
		'count_ignored_homogeneous_space_compaction_': [544],
		'count_performed_homogeneous_space_compaction_': [548],
		'concurrent_gc_pending_': [552],
		'pending_collector_transition_': [556],
		'pending_heap_trim_': [560],
		'use_homogeneous_space_compaction_for_oom_': [564],
		'running_collection_is_blocking_': [565],
		'blocking_gc_count_': [568],
		'blocking_gc_time_': [576],
		'last_update_time_gc_count_rate_histograms_': [584],
		'gc_count_last_window_': [592],
		'blocking_gc_count_last_window_': [600],
		'gc_count_rate_histogram_': [608],
		'blocking_gc_count_rate_histogram_': [708],
		'alloc_tracking_enabled_': [808],
		'allocation_records_': [812],
		'backtrace_lock_': [816],
		'seen_backtrace_count_': [824],
		'unique_backtrace_count_': [832],
		'seen_backtraces_': [840],
		'gc_disabled_for_shutdown_': [860],
		'boot_image_spaces_': [864],
		'alloc_listener_': [876],
		'gc_pause_listener_': [880],
		'verification_': [884],
	}],

	'FieldId': [0x8, {
		'class_idx_': [0],
		'type_idx_': [2],
		'name_idx_': [4],
	}],

	'TypeId': [0x4, {
		'descriptor_idx_': [0],
	}],

	'StringId': [0x4, {
		'string_data_off_': [0],
	}],

	'MethodId': [0x8, {
		'class_idx_': [0],
		'proto_idx_': [2],
		'name_idx_': [4],
	}],

	'Field': [0x20, {
		'padding_': [10],
		'declaring_class_': [12],
		'type_': [16],
		'access_flags_': [20],
		'dex_field_index_': [24],
		'offset_': [28],
	}],

	'ContinuousMemMapAllocSpace': [0x34, {
		'live_bitmap_': [40],
		'mark_bitmap_': [44],
		'temp_bitmap_': [48],
	}],

	'MemMapSpace': [0x24, {
		'mem_map_': [32],
	}],

	'RegionSpace': [0xb0, {
		'region_lock_': [56],
		'time_': [96],
		'num_regions_': [100],
		'num_non_free_regions_': [104],
		'num_evac_regions_': [108],
		'max_peak_num_non_free_regions_': [112],
		'regions_': [116],
		'non_free_region_index_limit_': [120],
		'current_region_': [124],
		'evac_region_': [128],
		'full_region_': [132],
		'mark_bitmap_': [172],
	}],

	'ContinuousSpace': [0x20, {
		'begin_': [20],
		'end_': [24],
		'limit_': [28],
	}],

	'AllocSpace': [0x4, {
		'_vptr$AllocSpace': [0],
	}],

	'ImageSpace': [0x3c, {
		'live_bitmap_': [36],
		'oat_file_': [40],
		'oat_file_non_owned_': [44],
		'image_location_': [48],
	}],

	'MallocSpace': [0x70, {
		'recent_freed_objects_': [52],
		'recent_free_pos_': [52],
		'lock_': [56],
		'growth_limit_': [96],
		'can_move_objects_': [100],
		'starting_size_': [104],
		'initial_size_': [108],
	}],

	'Region': [0x28, {
		'idx_': [0],
		'begin_': [4],
		'top_': [8],
		'end_': [12],
		'state_': [16],
		'type_': [17],
		'objects_allocated_': [20],
		'alloc_time_': [24],
		'live_bytes_': [28],
		'is_newly_allocated_': [32],
		'is_a_tlab_': [33],
		'thread_': [36],
	}],

	# MANUALLY ADDED - Based on other offset files
	# and AndroidXRef for Android 9.0.0_r3, /art/runtime/dex_file.h
	'DexFile': [0x58, {
		'_vptr$DexFile': [0],
		'begin_': [4],
		'size_': [8],
		'data_begin_': [12],
		'data_size_': [16],
		'location_': [20],
		'location_checksum_': [32],
		'header_': [36],
		'string_ids_': [40],
		'type_ids_': [44],
		'field_ids_': [48],
		'method_ids_': [52],
		'proto_ids_': [56],
		'class_defs_': [60],
		'method_handles_': [64],
		'num_method_handles_': [68],
		'call_site_ids_': [72],
		'oat_dex_file_': [76],
		'container_': [80],
		'is_compact_dex_': [84],
		'is_platform_dex_': [85],
	}],
	
	'SpaceBitmap':[0x1c,{
		'mem_map_' : [0],
		'bitmap_begin_' :[4],
		'bitmap_size_':[8],
		'heap_begin_': [12],
		'name_': [16],
	}],
}